USE MAIC
CREATE TABLE Events(
	Event_Key INT PRIMARY KEY NOT NULL IDENTITY,
	Start_Time DATETIME NOT NULL,
	End_Time DATETIME NOT NULL,
	Location VARCHAR(255) NOT NULL,
	Ext_Partner_Host BIT NOT NULL,
	Primary_MAIC VARCHAR(100),
	Secondary_MAIC VARCHAR(100),
	Tertiary_MAIC VARCHAR(100),
	Partners BIT NOT NULL,
	Primary_Partner VARCHAR(100),
	Secondary_Partner VARCHAR(100),
	Primary_Act VARCHAR(100) NOT NULL,
	Secondary_Act VARCHAR(100),
	Tertiary_Act VARCHAR(100),
	Other_Act VARCHAR(max),
	Staff_Lead VARCHAR(100) NOT NULL,
	Other_Staff VARCHAR(max),
	Total_Vols INT,
	Pop_Target INT,
	Primary_Fund VARCHAR(100),
	Secondary_Fund VARCHAR(100),
	Tertiary_Fund VARCHAR(100),
	Food_Drink BIT NOT NULL,
	Food_Drink_Provider VARCHAR(1000),
	Food_Drink_Consumed VARCHAR(1000),
	Sign_In BIT NOT NULL,
	CONSTRAINT Primary_Partner_Involvement CHECK ((Primary_Partner IS NOT NULL) OR (Ext_Partner_Host = 0 AND Partners = 0)),
	CONSTRAINT Internal_Host CHECK (Ext_Partner_Host = 1 OR Primary_MAIC IS NOT NULL),
	CONSTRAINT Food_Drink_Present CHECK ((Food_Drink = 1 AND Food_Drink_Provider IS NOT NULL AND Food_Drink_Consumed IS NOT NULL) OR (Food_Drink = 0 AND Food_Drink_Provider IS NULL AND Food_Drink_Consumed IS NULL))
);