INSERT INTO MAICPrograms (name) VALUES ('MAIC General');
INSERT INTO MAICPrograms (name) VALUES ('Culture/Languages Arts');
INSERT INTO MAICPrograms (name) VALUES ('Two Rivers/Arts');
INSERT INTO MAICPrograms (name) VALUES ('ICWA/Bright Beginnings');
INSERT INTO MAICPrograms (name) VALUES ('Indigenous Women''s Life Net');
INSERT INTO MAICPrograms (name) VALUES ('Fitness and Nutrition');
INSERT INTO MAICPrograms (name) VALUES ('Elders Program');
INSERT INTO MAICPrograms (name) VALUES ('Gatherings Café');
INSERT INTO MAICPrograms (name) VALUES ('Ginew/Golden Eagles');
INSERT INTO MAICPrograms (name) VALUES ('Employment/Training');